version: "3"
services:
  db:
    container_name: polla_db_prod
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /data/db # Create a volume for the DB.
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
  client:
    container_name: polla_client_prod
    build:
      context: ./client
      args:
        - REACT_APP_BASE_URL=${CLIENT_BASE_URL}
        - REACT_APP_API_BASE_URL=${API_BASE_URL}
        - REACT_APP_GITHUB_URL=${GITHUB_URL}
      dockerfile: Dockerfile.prod
    ports:
      - "${CLIENT_PORT}:3000"
    restart: always
  server:
    container_name: polla_server_prod
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=production
      - PORT=${API_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - APP_BASE_URL=${CLIENT_BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_EXPIRATION=${JWT_SECRET_EXPIRATION}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_SECRET_EXPIRATION=${JWT_REFRESH_SECRET_EXPIRATION}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${API_PORT}:8081"
    restart: always
  redis:
    container_name: polla_redis_prod
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
